version: "3.8"
name: "nekosauce"
services:
  backend:
    build: ./backend
    command: "/bin/sh -c \"/app/run.sh\""
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    environment:
      WORKERS: 4
  frontend:
    build: ./frontend
    command: "npm run start"
    ports:
      - "3000:3000"
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nekosauce
      - POSTGRES_PASSWORD=nekosauce
      - POSTGRES_DB=nekosauce
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "nekosauce", "-U", "nekosauce"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  database: